import { Platform, StyleSheet } from "react-native";
import { colors } from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../../Utils/helpers";


const TipSummaryScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerContainer: {
    height: getHeightEquivalent(40),
    width: "100%",
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: getWidthEquivalent(20),
    paddingRight: getWidthEquivalent(20),
  },
  TableContainer: {
    flexDirection: "row",
    justifyContent: "center",
  },
  backArrow: {
    height: "100%",
    width: getHeightEquivalent(80),
    justifyContent: "center",
  },
  headerButtons: {
    flexDirection: "row",
    height: "100%",
    gap: getWidthEquivalent(10),
  },
  addButton: {
    height: "100%",
    width: getHeightEquivalent(80),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: `${colors.white}`,
    flexDirection: "row",
  },
  addButtonText: {
    color: colors.black,
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "600",
  },
  filter: {
    height: "100%",
    width: getHeightEquivalent(50),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: colors.white,
    borderColor: colors.border,
    flexDirection: "row",
  },
  titleSection: {
    width: "100%",
    paddingHorizontal: getWidthEquivalent(20),
    paddingTop: getHeightEquivalent(16),
    paddingBottom: getHeightEquivalent(20),
    backgroundColor: colors.white,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: getHeightEquivalent(8),
  },
  title: {
    fontSize:Platform.OS === 'android' ?fontEq(18): fontEq(22),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "700",
    color: colors.text,
    flex: 1,
  },
  subtitle: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    color: colors.textSecondary,
    lineHeight: getHeightEquivalent(20),
    marginBottom: getHeightEquivalent(16),
  },
  contentContainer: {
    flexGrow: 1,
    backgroundColor: colors.white,
    paddingBottom: getHeightEquivalent(20),
  },
  tableContainer: {
    flex: 1,
    backgroundColor: colors.white,
    //paddingTop: getHeightEquivalent(10),
  },
  horizontalScroll: {
    flex: 1,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(40),
    paddingVertical: getHeightEquivalent(60),
  },
  emptyTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(18),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "600",
    color: colors.text,
    marginTop: getHeightEquivalent(16),
    marginBottom: getHeightEquivalent(8),
  },
  emptySubtitle: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: getHeightEquivalent(20),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(80),
  },
  loadingText: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    color: colors.textSecondary,
    marginTop: getHeightEquivalent(16),
    fontWeight: "500",
  },
  dateRangeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    borderRadius: 8,
    paddingHorizontal: getWidthEquivalent(12),
    height: getHeightEquivalent(44),
    width: "100%",
  },
  dateRangeText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    color: colors.text,
    fontWeight: "500",
  },
  countBadge: {
    backgroundColor: colors.background,
    borderRadius: 12,
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(4),
    marginLeft: getWidthEquivalent(8),
  },
  countText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "600",
    color: colors.text,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: 8,
    paddingHorizontal: getWidthEquivalent(12),
    height: getHeightEquivalent(44),
    marginBottom: getHeightEquivalent(12),
  },
  searchInput: {
    flex: 1,
    marginLeft: getWidthEquivalent(8),
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    color: colors.text,
    paddingVertical: 0,
    height: "100%",
  },
  bottomSheetContainer: {
    flex: 1,
    paddingHorizontal: getWidthEquivalent(20),
    paddingTop: getHeightEquivalent(10),
    paddingBottom: getHeightEquivalent(100),
  },
  bottomSheetTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(18): fontEq(20),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(8),
    textAlign: "center",
  },
  bottomSheetSubtitle: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    color: colors.textSecondary,
    marginBottom: getHeightEquivalent(20),
    textAlign: "center",
  },
  exportOptionsContainer: {
    gap: getHeightEquivalent(12),
  },
  exportOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(16),
    paddingHorizontal: getWidthEquivalent(16),
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  exportIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: getWidthEquivalent(16),
  },
  exportOptionText: {
    flex: 1,
  },
  exportOptionTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 2,
  },
  exportOptionDescription: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(13),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    color: colors.textSecondary,
  },
  backdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
});

export default TipSummaryScreenStyles;