import { StyleSheet } from "react-native";
import colors from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../../Utils/helpers";

const PerformanceDashboardScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.colors.white,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: getHeightEquivalent(50),
    paddingRight: getWidthEquivalent(20),
    paddingLeft: getWidthEquivalent(15),
    paddingVertical: getHeightEquivalent(16),
  },
  backButton: {
    height: getHeightEquivalent(50),
    alignItems: "center",
    // justifyContent: "center",
    borderRadius: 10,
    flexDirection: "row",
    paddingRight: getWidthEquivalent(10),
  },
  backButtonText: {
    fontSize: fontEq(18),
    fontWeight: "700",
    color: colors.colors.text,
  },
  starContainer: {
    position: "absolute",
    right: getWidthEquivalent(80),
  },
  optionButton: {
    height: getHeightEquivalent(40),
    // width: getWidthEquivalent(40),
    borderWidth: 1,
    borderColor: colors.colors.border,
    alignItems: "center",
    alignSelf: "center",
    // justifyContent: "center",
    borderRadius: 10,
    flexDirection: "row",
    paddingHorizontal: getWidthEquivalent(10),
  },
  titleContainer: {
    height: getHeightEquivalent(160),
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(10),
  },
  title: {
    fontSize: fontEq(24),
    fontWeight: "700",
    color: colors.colors.text,
    marginBottom: getHeightEquivalent(10),
  },
  description: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.colors.textSecondary,
    marginBottom: getHeightEquivalent(30),
  },
  filterButton: {
    height: getHeightEquivalent(40),
    width: getWidthEquivalent(40),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: colors.colors.border,
    marginRight: getWidthEquivalent(10),
  },
  filterContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  filterOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  filterOptionIcon: {
    marginRight: getWidthEquivalent(15),
  },
  dateButton: {
    height: getHeightEquivalent(40),
    width: getWidthEquivalent(180),
    paddingHorizontal: getWidthEquivalent(10),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: colors.colors.border,
  },
  contentContainer: {
    flex: 1,
    // paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(20),
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: getWidthEquivalent(13),
    marginHorizontal: getWidthEquivalent(20),
  },
  sectionContainer: {
    width: "48%",
    paddingVertical: getHeightEquivalent(20),
    paddingHorizontal: getWidthEquivalent(16),
    borderWidth: 1,
    borderColor: colors.colors.border,
    borderRadius: 12,
    backgroundColor: colors.colors.white,
    marginBottom: getHeightEquivalent(15),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: colors.colors.textSecondary,
    marginBottom: getHeightEquivalent(10),
  },
  sectionAmount: {
    fontSize: fontEq(22),
    fontWeight: "700",
    color: colors.colors.text,
    marginBottom: getHeightEquivalent(8),
  },
  compareContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: getHeightEquivalent(8),
  },
  compareText: {
    fontSize: fontEq(12),
    color: colors.colors.success,
    fontWeight: "500",
    marginLeft: getWidthEquivalent(4),
  },
  // Sales by Channel Table Styles
  tableSection: {
    marginTop: getHeightEquivalent(30),
    backgroundColor: colors.colors.white,
    borderRadius: 12,
    padding: getWidthEquivalent(10),
    borderWidth: 1,
    borderColor: colors.colors.border,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  tableSectionTitle: {
    fontSize: fontEq(18),
    fontWeight: "700",
    color: colors.colors.text,
    marginBottom: getHeightEquivalent(8),
  },
  tableSectionSubtitle: {
    fontSize: fontEq(14),
    color: colors.colors.textSecondary,
    marginBottom: getHeightEquivalent(20),
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.colors.primaryLight || colors.colors.gray[100],
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(16),
    // paddingLeft: getWidthEquivalent(16),
    borderRadius: 8,
    marginBottom: getHeightEquivalent(8),
  },
  tableHeaderText: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: colors.colors.text,
    textAlign: "left",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(16),
    borderBottomWidth: 1,
    borderBottomColor: colors.colors.border,
  },
  tableRowTotal: {
    backgroundColor: colors.colors.primaryLight || colors.colors.gray[50],
    borderRadius: 8,
    marginTop: getHeightEquivalent(8),
    borderBottomWidth: 0,
  },
  tableCellType: {
    flex: 2,
    alignItems: "flex-start",
  },
  tableCellSales: {
    flex: 1.5,
    alignItems: "flex-end",
    marginRight: getWidthEquivalent(3),
  },
  tableCellPercentage: {
    flex: 1.5,
    alignItems: "flex-end",
  },
  tableCellAverage: {
    flex: 2,
    alignItems: "flex-end",
  },
  tableCellText: {
    fontSize: fontEq(12),
    color: colors.colors.text,
    fontWeight: "400",
  },
  tableCellTextTotal: {
    fontSize: fontEq(12),
    color: colors.colors.text,
    fontWeight: "700",
  },
  // Filter Panel Styles
  filterPanelModal: {
    margin: 0, // full screen - covers entire screen
    justifyContent: "flex-start", // align to top
    alignItems: "flex-end", // align to right
  },
  filterPanel: {
    width: "100%", // Full width - covers entire screen
    height: "100%", // Full height - covers entire screen
    backgroundColor: colors.colors.white,
    shadowColor: "#000",
    shadowOffset: {
      width: -2,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 10,
  },
  filterPanelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(20),
    // marginTop:getHeightEquivalent(20),
    paddingTop: getHeightEquivalent(40),
    borderBottomWidth: 1,
    borderBottomColor: colors.colors.border,
    // backgroundColor:"red"
  },
  filterPanelTitle: {
    fontSize: fontEq(20),
    fontWeight: "700",
    color: colors.colors.text,
  },
  filterCloseButton: {
    padding: getWidthEquivalent(8),
    borderRadius: 20,
    backgroundColor: colors.colors.gray[100],
  },
  filterPanelContent: {
    flex: 1,
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(20),
  },
  filterOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(16),
    borderBottomWidth: 1,
    borderBottomColor: colors.colors.border,
  },
  filterOptionText: {
    fontSize: fontEq(16),
    color: colors.colors.text,
    fontWeight: "500",
  },
  filterPanelButtons: {
    flexDirection: "row",
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(20),
    borderTopWidth: 1,
    borderTopColor: colors.colors.border,
    gap: getWidthEquivalent(12),
  },
  filterClearButton: {
    flex: 1,
    paddingVertical: getHeightEquivalent(16),
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.colors.border,
    backgroundColor: colors.colors.white,
  },
  filterApplyButton: {
    flex: 1,
    paddingVertical: getHeightEquivalent(16),
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.colors.primary,
  },
  filterClearButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.colors.text,
  },
  filterApplyButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.colors.white,
  },
  accordionContent: {
    height: getHeightEquivalent(25),
    width: getWidthEquivalent(100),
    borderWidth: 1,
    //  alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  checkBox: {
    height: "80%",
    width: getWidthEquivalent(20),
    borderWidth: 2,
    borderColor: colors.colors.text,
    borderRadius: 3,
  },
  checkBoxActive: {
    height: "80%",
    width: getWidthEquivalent(20),
    borderRadius: 3,
    backgroundColor: colors.colors.primaryDark,
  },
  lineGraphSection: {
    marginTop: getHeightEquivalent(30),
    backgroundColor: colors.colors.white,
    marginHorizontal: getWidthEquivalent(10),
    // height: getHeightEquivalent(400),
    borderRadius: 12,
    padding: getWidthEquivalent(10),
    borderWidth: 1,
    borderColor: colors.colors.border,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  lineAmount: {
    fontSize: fontEq(16),
    fontWeight: "700",
    color: colors.colors.text,
  },
  lineGraphDetails: {
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "space-between",
    // borderWidth: 1,
    // height: getHeightEquivalent(40),
    marginLeft: getWidthEquivalent(5),
  },
  lineGraphDetailsContainer: {
    // flex: 1,
    // height: getHeightEquivalent(30),
    // width: "40%",
    flexDirection: "row",
    alignItems: "center",
    marginTop: getHeightEquivalent(10),
    //borderWidth: 1,
  },
  lineGraphText: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: colors.colors.text,
    marginLeft: getWidthEquivalent(5),
  },
  lineGraphWrapContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    //borderWidth: 1,
    overflow: "hidden",
    height: getHeightEquivalent(280),
    marginTop: getHeightEquivalent(30),
    // paddingTop: getHeightEquivalent(10),
    // paddingBottom: getHeightEquivalent(40),
    backgroundColor: colors.colors.white,
  },
  barGraphContainer: {
    marginTop: getHeightEquivalent(30),
    backgroundColor: colors.colors.white,
    marginHorizontal: getWidthEquivalent(10),
    // height: getHeightEquivalent(400),
    borderRadius: 12,
    padding: getWidthEquivalent(10),
    borderWidth: 1,
    borderColor: colors.colors.border,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  barGraphDetailsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(10),
    height: getHeightEquivalent(40),
    marginTop: getHeightEquivalent(10),
  },
  barGraphWrapper: {
    height: getHeightEquivalent(250),
    marginTop: getHeightEquivalent(10),
    // borderWidth: 1,
    alignItems: "flex-end",
    justifyContent: "space-around",
    paddingVertical: getHeightEquivalent(20),
    flexDirection: "row",
  },
});
export default PerformanceDashboardScreenStyles;
