import { Platform, StyleSheet } from "react-native";
import { colors } from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../../Utils/helpers";

export const AddClientStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.white,
  },
  closeButton: {
    width: getWidthEquivalent(40),
    height: getWidthEquivalent(40),
    borderRadius: getWidthEquivalent(20),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
  },
  headerTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(20),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "700",
    color: colors.text,
    flex: 1,
    textAlign: "left",
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: getWidthEquivalent(16),
  },
  section: {
    marginBottom: getHeightEquivalent(20),
  },
  row: {
    flexDirection: "row",
    gap: getWidthEquivalent(12),
    marginBottom: getHeightEquivalent(20),
  },
  halfWidth: {
    flex: 1,
  },
  label: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(8),
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: getWidthEquivalent(8),
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
    backgroundColor: colors.white,
  },
  inputError: {
    borderColor: colors.danger,
    borderWidth: 2,
  },
  generalErrorContainer: {
    backgroundColor: colors.danger + "10",
    borderWidth: 1,
    borderColor: colors.danger,
    borderRadius: getWidthEquivalent(8),
    padding: getWidthEquivalent(12),
    marginBottom: getHeightEquivalent(16),
  },
  generalErrorText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.danger,
    textAlign: "center",
  },
  errorText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(12),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.danger,
    marginTop: getHeightEquivalent(4),
  },
  phoneContainer: {
    flexDirection: "row",
    gap: getWidthEquivalent(8),
  },
  countryCodeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: getWidthEquivalent(8),
    paddingHorizontal: getWidthEquivalent(12),
    paddingVertical: getHeightEquivalent(8),
    gap: getWidthEquivalent(4),
    minWidth: getWidthEquivalent(100),
  },
  countryCodeText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
    fontWeight: "500",
  },
  countryNameText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(12),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.textSecondary,
    marginTop: getHeightEquivalent(2),
  },
  phoneInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: getWidthEquivalent(8),
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
  },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: getWidthEquivalent(8),
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
  },
  dateButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
  },
  placeholderText: {
    color: colors.gray[300],
  },
  textArea: {
    minHeight: getHeightEquivalent(70),
    textAlignVertical: "top",
  },
  dropdownButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: getWidthEquivalent(8),
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
  },
  dropdownButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
  },
  saveButton: {
    backgroundColor: colors.black,
    borderRadius: getWidthEquivalent(50),
    paddingVertical: getHeightEquivalent(16),
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(20),
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
      fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.white,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: getWidthEquivalent(20),
    borderTopRightRadius: getWidthEquivalent(20),
    padding: getWidthEquivalent(20),
    height: "90%",
  },
  modalDragIndicator: {
    width: getWidthEquivalent(40),
    height: getHeightEquivalent(5),
    borderRadius: getWidthEquivalent(3),
    backgroundColor: colors.gray[300],
    alignSelf: "center",
    marginTop: getHeightEquivalent(10),
    marginBottom: getHeightEquivalent(15),
  },
  modalTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(18),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(16),
    textAlign: "left",
  },
  modalItem: {
    paddingVertical: getHeightEquivalent(14),
    paddingHorizontal: getWidthEquivalent(16),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalItemText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.black,
  },
  modalCloseButton: {
    marginTop: getHeightEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    alignItems: "center",
    backgroundColor: colors.gray[200],
    borderRadius: getWidthEquivalent(50),
  },
  modalCloseButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "500",
    color: colors.text,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(50),
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: getWidthEquivalent(12),
    paddingVertical: Platform.OS === 'android' ?getHeightEquivalent(2) : getHeightEquivalent(12),
    marginBottom: getHeightEquivalent(16),
    gap: getWidthEquivalent(8),
  },
  searchInput: {
    flex: 1,
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
  },
  loadingContainer: {
    paddingVertical: getHeightEquivalent(40),
    alignItems: "center",
    justifyContent: "center",
  },
  countryList: {
    maxHeight: getHeightEquivalent(500),
  },
  emptyContainer: {
    paddingVertical: getHeightEquivalent(40),
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.textSecondary,
    textAlign: "center",
  },
});
