import { StyleSheet, Text, View } from "react-native";
import colors from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../../Utils/helpers";

const { colors: paint } = colors;
export const ClientScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    // justifyContent: "center",
    alignItems: "center",
    backgroundColor: paint.white,
  },
  header: {
    width: "100%",
    height: getHeightEquivalent(50),
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    backgroundColor: paint.white,
    borderBottomWidth: 1,
    paddingLeft: getWidthEquivalent(20),
    borderBottomColor: paint.border,
  },
  actionContainer: {
    //width: "100%",
    height: getHeightEquivalent(50),
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: paint.white,
    paddingRight: getWidthEquivalent(20),
    marginBottom: getHeightEquivalent(0.5),
  },
  actionButton: {
    flexDirection: "row",
    paddingHorizontal: getWidthEquivalent(8),
    paddingVertical: getHeightEquivalent(8),
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: paint.white,
    borderColor: paint.border,
    width: getWidthEquivalent(80),
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  actionButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.text,
  },
  elipseContainer: {
    height: getHeightEquivalent(60),
    width: getWidthEquivalent(60),
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    fontSize: fontEq(17),
    fontWeight: "600",
    color: paint.text,
    marginTop: getHeightEquivalent(15),
    alignSelf: "center",
    lineHeight: getHeightEquivalent(28),
    marginBottom: getHeightEquivalent(12),
  },
  bodyContainer: {
    flex: 1,
    width: "100%",
    // height: getHeightEquivalent(300),

    //justifyContent: "center",
    backgroundColor: paint.white,
  },
  titleContentContainer: {
    width: "100%",
    backgroundColor: paint.white,
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(15),
    //marginBottom: getHeightEquivalent(5),
  },
  title: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: paint.text,
    // marginLeft: getWidthEquivalent(12),
    // marginTop: getHeightEquivalent(15),
    //alignSelf: "center",
    lineHeight: getHeightEquivalent(28),
  },
  subTitle: {
    fontSize: fontEq(15),
    fontWeight: "400",
    color: paint.text,
    marginTop: getHeightEquivalent(8),
    lineHeight: getHeightEquivalent(20),
  },
  learnMore: {
    fontSize: fontEq(15),
    fontWeight: "400",
    color: paint.primary,
    marginTop: getHeightEquivalent(5),
    lineHeight: getHeightEquivalent(20),
  },
  searchFilterContainer: {
    height: getHeightEquivalent(50),
    width: "100%",
    backgroundColor: paint.white,
    alignSelf: "center",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(20),
    marginBottom: getHeightEquivalent(10),
  },
  filterContainer: {
    height: getHeightEquivalent(50),
    width: "14%",
    backgroundColor: paint.white,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: paint.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  searchContainer: {
    height: getHeightEquivalent(50),
    width: "80%",
    backgroundColor: paint.white,
    borderWidth: 1,
    borderColor: paint.border,
    alignItems: "center",
    borderRadius: 10,
    paddingHorizontal: getWidthEquivalent(15),
    flexDirection: "row",
  },
  searchInput: {
    height: "70%",
    width: "80%",
    marginLeft: getWidthEquivalent(10),
  },
  clientCardContainer: {
    height: getHeightEquivalent(80),
    width: "100%",
    backgroundColor: paint.white,
    flexDirection: "row",
    marginBottom: getHeightEquivalent(10),
    paddingHorizontal: getWidthEquivalent(20),
    alignItems: "center",
  },
  clientImageContainer: {
    height: getHeightEquivalent(50),
    width: getHeightEquivalent(50),
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5E7FD",
  },
  clientDetailsContainer: {
    height: "100%",
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: getWidthEquivalent(15),
  },
  clientInfo: {
    flexShrink: 1,
    marginRight: getWidthEquivalent(12),
  },
  clientName: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.text,
    marginBottom: getHeightEquivalent(3),
  },
  clientEmail: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: paint.textSecondary,
    marginBottom: getHeightEquivalent(5),
  },
  clientPhone: {
    fontSize: fontEq(14),
    color: paint.textSecondary,
  },
  clientInitials: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: "#3C096C",
  },
  clientSalesBadge: {
    backgroundColor: paint.gray[100],
    borderRadius: 10,
    paddingVertical: getHeightEquivalent(6),
    paddingHorizontal: getWidthEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  clientSales: {
    fontSize: fontEq(13),
    fontWeight: "600",
    color: paint.gray[700],
  },
  clearButton: {
    padding: getWidthEquivalent(5),
    marginLeft: getWidthEquivalent(5),
  },
  loadMoreButton: {
    backgroundColor: paint.white,
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(20),
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: getWidthEquivalent(20),
    borderWidth: 1,
    borderColor: paint.border,
  },
  loadMoreText: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: paint.text,
  },
  emptyStateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: getWidthEquivalent(40),
    paddingVertical: getHeightEquivalent(60),
  },
  emptyStateTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: paint.text,
    textAlign: "center",
    marginBottom: getHeightEquivalent(8),
  },
  emptyStateSubtitle: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: paint.textSecondary,
    textAlign: "center",
    lineHeight: getHeightEquivalent(20),
    marginBottom: getHeightEquivalent(20),
  },
  addFirstClientButton: {
    backgroundColor: paint.primary,
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(24),
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  addFirstClientText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: paint.white,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: getHeightEquivalent(40),
  },
  loadingText: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: paint.textSecondary,
    marginTop: getHeightEquivalent(10),
  },
});
