import { Platform, StyleSheet } from "react-native";
import colors from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../../Utils/helpers";

const paint = colors.colors;
export const DailySalesScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: paint.white,
  },
  headerContainer: {
    height: getHeightEquivalent(40),
    width: "100%",
    borderColor: paint.border,
    backgroundColor: paint.white,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: getWidthEquivalent(20),
    paddingRight: getWidthEquivalent(20),
  },
  backArrow: {
    height: "100%",
    width: getHeightEquivalent(80),
    justifyContent: "center",
  },
  filter: {
    height: "100%",
    width: getHeightEquivalent(50),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: paint.white,
    borderColor: paint.border,
    flexDirection: "row",
  },
  addButton: {
    height: "100%",
    width: getHeightEquivalent(80),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: paint.black,
    flexDirection: "row",
  },
  addButtonText: {
    color: paint.white,
    fontSize: fontEq(14),
    fontWeight: "600",
    marginLeft: getWidthEquivalent(10),
  },
  elipseBox: {
    position: "absolute",
    right: getWidthEquivalent(80),
    height: "100%",
    width: getWidthEquivalent(45),
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: paint.border,
    borderRadius: 8,
    backgroundColor: paint.white,
    flexDirection: "row",
  },
  bodyContainer: {
    flex: 1,
    backgroundColor: paint.white,
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(20),
  },
  bodyTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(18): fontEq(28),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: paint.text,
  },
  bodySubtitle: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(13),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: paint.textSecondary,
    marginTop: getHeightEquivalent(10),
  },
  dateNavigationContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(20),
    gap: getWidthEquivalent(10),
  },
  todayButton: {
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(8),
    borderWidth: 1,
    borderColor: paint.primary,
    borderRadius: 8,
    backgroundColor: paint.primary,
  },
  todayButtonDisabled: {
    backgroundColor: paint.border,
    borderColor: paint.border,
  },
  todayButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "500",
    color: paint.white,
  },
  todayButtonTextDisabled: {
    color: paint.textMuted,
  },
  chevronButton: {
    width: getWidthEquivalent(40),
    height: getHeightEquivalent(40),
    borderWidth: 1,
    borderColor: paint.border,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: paint.white,
  },
  filterButton: {
    flexDirection: "row",
    width: "50%",
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(8),
    borderWidth: 1,
    borderColor: paint.border,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  disabledFilterButton: {
    backgroundColor: colors.colors.gray[300],
    opacity: 0.6,
  },

  filterButtonText: {
        fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "500",
    color: colors.colors.black,
    marginRight: getWidthEquivalent(10),
  },
  titleSection: {
    backgroundColor: paint.white,
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(20),
    borderBottomWidth: 1,
    borderBottomColor: paint.border,
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: paint.white,
  },
  scrollContent: {
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(20),
    paddingBottom: getHeightEquivalent(40),
  },
  sectionTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(22),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: paint.text,
    marginBottom: getHeightEquivalent(10),
    marginTop: getHeightEquivalent(10),
    marginLeft: getWidthEquivalent(10),
  },
  transactionSummary: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(22),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: paint.text,
    marginBottom: getHeightEquivalent(10),
    marginTop: getHeightEquivalent(10),
  },
  // Bottom sheet styles
  backdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 999,
  },
  bottomSheetContainer: {
    flex: 1,
    paddingHorizontal: getWidthEquivalent(20),
    paddingTop: getHeightEquivalent(10),
  },
  bottomSheetTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(20),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "700",
    color: paint.text,
    textAlign: "center",
    marginBottom: getHeightEquivalent(8),
  },
  bottomSheetSubtitle: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "400",
    color: paint.textSecondary,
    textAlign: "center",
    marginBottom: getHeightEquivalent(30),
  },
  exportOptionsContainer: {
    gap: getHeightEquivalent(16),
  },
  exportOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: getWidthEquivalent(16),
    borderRadius: 12,
    borderWidth: 1,
    borderColor: paint.border,
    backgroundColor: paint.white,
  },
  exportIconContainer: {
    width: getWidthEquivalent(48),
    height: getWidthEquivalent(48),
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: getWidthEquivalent(16),
  },
  exportOptionText: {
    flex: 1,
  },
  exportOptionTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "600",
    color: paint.text,
    marginBottom: getHeightEquivalent(4),
  },
  exportOptionDescription: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(13),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "400",
    color: paint.textSecondary,
  },
});
