import { StyleSheet } from "react-native";
import colors from "../../../Constants/colors";
import {
  getHeightEquivalent,
  getWidthEquivalent,
  fontEq,
} from "../../../Utils/helpers";
const { colors: paint } = colors;
export const DashBoardScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: paint.backgroundSecondary,
  },
  downloadButtonContainer: {
    height: getHeightEquivalent(40),
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: paint.white,
    //borderWidth: 1,
    //marginTop: getHeightEquivalent(5),
    marginBottom: getHeightEquivalent(15),
  },
  downloadButton: {
    height: "100%",
    flexDirection: "row",
    width: "30%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: paint.white,
    borderWidth: 1,
    borderColor: paint.border,
    borderRadius: 5,
  },
  downloadButtonText: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.textSecondary,
    marginLeft: getWidthEquivalent(5),
  },
  Header: {
    // height: getHeightEquivalent(60),
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(5),
    backgroundColor: paint.white,
    shadowColor: paint.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: paint.border,
    paddingTop: getHeightEquivalent(40),
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    // paddingHorizontal: getWidthEquivalent(8),
    paddingVertical: getHeightEquivalent(8),
  },
  backIcon: {
    color: paint.text,
  },
  backText: {
    fontSize: fontEq(16),
    fontWeight: "500",
    color: paint.black,
    marginLeft: getWidthEquivalent(8),
  },
  body: {
    flex: 1,
    //justifyContent: "center",
    //alignItems: "center",
    paddingHorizontal: getWidthEquivalent(5),
    //borderWidth: 1,
  },
  title: {
    fontSize: fontEq(20),
    fontWeight: "700",
    color: paint.text,
    marginLeft: getWidthEquivalent(8),
    marginTop: getHeightEquivalent(15),
  },
  sectionContainer: {
    paddingHorizontal: getWidthEquivalent(10),
    paddingTop: getHeightEquivalent(16),
    paddingBottom: getHeightEquivalent(20),
    marginHorizontal: getWidthEquivalent(10),
    marginTop: getHeightEquivalent(15),
    marginBottom: getHeightEquivalent(15),
    backgroundColor: paint.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: paint.border,
  },
  sectionTitle: {
    fontSize: fontEq(20),
    fontWeight: "700",
    color: paint.text,
    marginLeft: getWidthEquivalent(8),
    marginBottom: getHeightEquivalent(15),
    //marginTop: getHeightEquivalent(15),
  },
  activityCard: {
    flexDirection: "row",
    height: getHeightEquivalent(115),
    width: "100%",
    // paddingHorizontal: getWidthEquivalent(10),
    //paddingVertical: getHeightEquivalent(16),
    backgroundColor: paint.white,
    borderColor: paint.border,
    borderBottomWidth: 1,
    marginBottom: getHeightEquivalent(15),
    paddingBottom: getHeightEquivalent(10),
  },
  lastActivityCard: {
    borderBottomWidth: 0,
    paddingBottom: 0,
    marginBottom: 0,
  },
  sectionScroll: {
    // borderWidth: 1,
    borderColor: paint.border,
    marginTop: getHeightEquivalent(20),
    marginHorizontal: getWidthEquivalent(8),
  },
  activityTitle: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: paint.textSecondary,
  },
  activityDateContainer: {
    width: "20%",
    height: "100%",
    borderColor: paint.border,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingRight: getWidthEquivalent(15),
  },
  activityDate: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: paint.text,
  },
  activityDate2: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.textSecondary,
  },
  activityContentContainer: {
    width: "80%",
    height: "100%",
    borderColor: paint.buttonPrimary,
    alignItems: "flex-start",

    //justifyContent: "space-between",
  },
  activityTime: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.textSecondary,
    marginTop: getHeightEquivalent(5),
  },
  activityService: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.text,
    marginTop: getHeightEquivalent(10),
  },
  activityClient: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: paint.textSecondary,
    marginTop: getHeightEquivalent(5),
  },
  statusContainer: {
    width: getWidthEquivalent(120),
    height: getHeightEquivalent(30),
    flexDirection: "row",
    position: "absolute",
    right: 0,
    justifyContent: "space-between",
    //paddingRight: getWidthEquivalent(15),
  },
  statusBar: {
    height: "100%",
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(2),
    backgroundColor: paint.primary,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 40,
    //paddingRight: getWidthEquivalent(15),
  },
  statusText: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.white,
  },
  barGraphTitle: {
    fontSize: fontEq(18),
    fontWeight: "700",
    color: paint.text,
    marginVertical: getHeightEquivalent(15),
    marginLeft: getWidthEquivalent(8),
  },
  barGraphSubTitle: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: paint.textSecondary,
    marginTop: getHeightEquivalent(5),
    marginLeft: getWidthEquivalent(6),
  },
  barGraphContainer: {
    height: getHeightEquivalent(200),
    width: "100%",
    // borderWidth: 1,
    //marginTop: getHeightEquivalent(15),
    marginBottom: getHeightEquivalent(65),
    backgroundColor: paint.white,
    alignItems: "flex-start",
    justifyContent: "center",
    overflow: "hidden",
  },
  barGraphFilter: {
    height: getHeightEquivalent(45),
    width: getWidthEquivalent(45),
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: getWidthEquivalent(10),
    top: getHeightEquivalent(10),
  },
  lineGraphTitle: {
    fontSize: fontEq(16),
    fontWeight: "700",
    color: paint.text,
    marginVertical: getHeightEquivalent(15),
    marginLeft: getWidthEquivalent(8),
  },
  lineGraphContainer: {
    height: getHeightEquivalent(250),
    marginTop: getHeightEquivalent(15),
    marginBottom: getHeightEquivalent(65),
    marginHorizontal: getWidthEquivalent(15),
    paddingVertical: getHeightEquivalent(15),
    backgroundColor: paint.gray[50],
    borderRadius: getWidthEquivalent(16),
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  // Table styles for top services
  tableHeaderContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(12),
    marginTop: getHeightEquivalent(15),
    backgroundColor: paint.backgroundSecondary,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: paint.border,
  },
  tableHeaderText: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.text,
    textAlign: "center",
  },
  tableScrollView: {
    marginTop: getHeightEquivalent(10),
    maxHeight: getHeightEquivalent(300),
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(15),
    borderBottomWidth: 1,
    borderBottomColor: paint.border,
    marginBottom: getHeightEquivalent(5),
  },
  lastTableRow: {
    borderBottomWidth: 0,
    marginBottom: 0,
  },
  tableServiceName: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: paint.text,
    textAlign: "center",
  },
  tableCount: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: paint.primary,
    textAlign: "center",
  },
  tableAmount: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: paint.primary,
    textAlign: "center",
  },
  noDataText: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: paint.textSecondary,
    textAlign: "center",
    marginTop: getHeightEquivalent(20),
  },

  // Date Picker Styles
  datePickerContainer: {
    marginTop: getHeightEquivalent(15),
    marginBottom: getHeightEquivalent(10),
    paddingHorizontal: getWidthEquivalent(10),
  },
  datePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: getWidthEquivalent(12),
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(8),
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(10),
    backgroundColor: paint.background,
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: paint.border,
  },
  datePickerButtonText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: paint.text,
  },
  datePickerSeparator: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: paint.textSecondary,
  },
  dateRangeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(12),
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(14),
    backgroundColor: paint.white,
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: paint.gray[300],
  },
  dateRangeLabel: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: paint.textSecondary,
    marginBottom: getHeightEquivalent(2),
  },
  dateRangeText: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.text,
  },

  // Pie Chart Styles
  pieChartSection: {
    marginTop: getHeightEquivalent(15),
    marginBottom: getHeightEquivalent(15),
    paddingVertical: getHeightEquivalent(15),
    paddingHorizontal: getWidthEquivalent(15),
    backgroundColor: paint.white,
    borderRadius: getWidthEquivalent(16),
    marginHorizontal: getWidthEquivalent(15),
  },
  pieChartTitle: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: paint.black,
    marginBottom: getHeightEquivalent(12),
    textAlign: "center",
  },
  pieChartCenterContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: getHeightEquivalent(15),
    paddingHorizontal: getWidthEquivalent(20),
  },
  pieChartContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(10),
    height: getHeightEquivalent(160),
  },
  pieChartEmptyContainer: {
    marginTop: getHeightEquivalent(15),
    marginBottom: getHeightEquivalent(15),
    paddingVertical: getHeightEquivalent(32),
    paddingHorizontal: getWidthEquivalent(20),
    marginHorizontal: getWidthEquivalent(15),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: paint.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: paint.border,
  },
  pieChartEmptyTitle: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.black,
    marginBottom: getHeightEquivalent(8),
    textAlign: "center",
  },
  pieChartEmptySubtitle: {
    fontSize: fontEq(13),
    fontWeight: "500",
    color: paint.textSecondary,
    textAlign: "center",
  },
  pieChartCenter: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  pieChartCenterValue: {
    fontSize: fontEq(12),
    fontWeight: "400",
    color: paint.black,
    textAlign: "center",
    width: "100%",
  },
  pieChartCenterLabel: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: paint.text,
    marginTop: getHeightEquivalent(2),
    textAlign: "center",
    width: "100%",
  },
  pieChartLegend: {
    flex: 1,
    marginLeft: getWidthEquivalent(15),
  },
  pieChartLegendHorizontal: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(10),
    marginTop: getHeightEquivalent(15),
    gap: getWidthEquivalent(12),
  },
  pieChartLegendContainer: {
    marginTop: getHeightEquivalent(16),
    gap: getHeightEquivalent(12),
  },
  pieChartLegendGroup: {
    width: "100%",
    backgroundColor: paint.white,
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: paint.border,
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(14),
    gap: getHeightEquivalent(8),
  },
  pieChartLegendGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pieChartLegendGroupHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(8),
  },
  pieChartLegendGroupTitle: {
    fontSize: fontEq(12),
    fontWeight: "700",
    color: paint.text,
  },
  pieChartLegendGroupTotal: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.primary,
  },
  pieChartLegendGroupBody: {
    gap: getHeightEquivalent(8),
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: getHeightEquivalent(8),
    gap: getWidthEquivalent(8),
  },
  legendItemHorizontal: {
    flexDirection: "column",
    alignItems: "center",
    gap: getHeightEquivalent(4),
    minWidth: getWidthEquivalent(60),
  },
  pieChartLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pieChartLegendRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(8),
  },
  pieChartLegendColor: {
    width: getWidthEquivalent(12),
    height: getWidthEquivalent(12),
    borderRadius: getWidthEquivalent(6),
  },
  pieChartLegendLabel: {
    fontSize: fontEq(11),
    fontWeight: "600",
    color: paint.text,
    marginLeft: getWidthEquivalent(5),
  },
  pieChartLegendRowRight: {
    alignItems: "flex-end",
    gap: getHeightEquivalent(2),
  },
  pieChartLegendValue: {
    fontSize: fontEq(11),
    fontWeight: "500",
    color: paint.text,
  },
  pieChartLegendPercent: {
    fontSize: fontEq(11),
    fontWeight: "500",
    color: paint.textSecondary,
  },
  pieChartLegendEmpty: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: paint.textSecondary,
    textAlign: "center",
    marginTop: getHeightEquivalent(10),
  },
  legendColor: {
    width: getWidthEquivalent(10),
    height: getWidthEquivalent(10),
    borderRadius: getWidthEquivalent(5),
  },
  legendTextHorizontal: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.text,
    maxWidth: getWidthEquivalent(120),
    textAlign: "center",
  },
  legendValueHorizontal: {
    fontSize: fontEq(12),
    fontWeight: "700",
    color: paint.text,
    textAlign: "center",
  },
  legendSubValue: {
    fontSize: fontEq(10),
    fontWeight: "500",
    color: paint.textSecondary,
    textAlign: "center",
    marginTop: getHeightEquivalent(2),
  },

  // Calendar Modal Styles
  calendarModal: {
    justifyContent: "flex-end",
    margin: 0,
  },
  calendarContainer: {
    backgroundColor: paint.white,
    borderTopLeftRadius: getWidthEquivalent(20),
    borderTopRightRadius: getWidthEquivalent(20),
    maxHeight: getHeightEquivalent(500),
    paddingBottom: getHeightEquivalent(20),
  },
  calendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(15),
    borderBottomWidth: 1,
    borderBottomColor: paint.border,
  },
  calendarTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: paint.text,
  },
  calendarCloseButton: {
    fontSize: fontEq(24),
    color: paint.textSecondary,
    fontWeight: "300",
  },
});
