import { StyleSheet } from "react-native";
import { colors } from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
  SCREEN_WIDTH,
} from "../../../Utils/helpers";

export const ReportDetailsScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    height: getHeightEquivalent(45), //60,
    //borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  backButton: {
    padding: getWidthEquivalent(8),
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    //width: getWidthEquivalent(40),
    height: getHeightEquivalent(40),
    flexDirection: "row",
    // Add some visual feedback
    backgroundColor: "transparent",
  },
  headerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: getWidthEquivalent(100), //100,
    borderWidth: 2,
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(6),
    borderRadius: 10,
    borderColor: colors.textMuted,
  },
  headerButtonText: {
    fontSize: fontEq(20), // 20,
    fontWeight: "500",
    color: colors.text,
  },
  headerText: {
    fontSize: fontEq(25),
    fontWeight: "600",
  },
  badgeContainer: {
    height: getHeightEquivalent(30),
    width: getWidthEquivalent(40),
    borderRadius: 38,
    borderWidth: 1,
    borderColor: colors.border,
    marginLeft: getWidthEquivalent(10),
  },
  badgeHeaderContianer: {
    flexDirection: "row",
    flexWrap: "wrap",
    // width: SCREEN_WIDTH,
    paddingHorizontal: getWidthEquivalent(15),
    paddingVertical: getHeightEquivalent(10),
    alignItems: "center",
  },
  subTextBadge: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: colors.text,
    marginTop: getHeightEquivalent(20),
  },
  searchFilterContainer: {
    //borderWidth: 1,
    borderColor: colors.black,
    height: getHeightEquivalent(45),
    width: getWidthEquivalent(SCREEN_WIDTH),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(15),
    marginTop: getHeightEquivalent(15),
  },
  searchContainer: {
    height: "100%",
    width: getWidthEquivalent(280),
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderRadius: 50,
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: getWidthEquivalent(10),
  },
  filterContainer: {
    height: "100%",
    width: getWidthEquivalent(50),
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  clearSearch: {
    width: getWidthEquivalent(24),
    height: getHeightEquivalent(24),
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  searchIcon: {
    width: getWidthEquivalent(24),
    alignItems: "center",
    justifyContent: "center",
  },
  searchInput: {
    flex: 1,
    height: "100%",
    marginLeft: getWidthEquivalent(10),
    fontSize: fontEq(16),
    color: colors.text,
    fontWeight: "500",
  },
  clearSearchContainer: {
    width: getWidthEquivalent(30),
    alignItems: "center",
    justifyContent: "center",
  },
  tabsContainer: {
    height: getHeightEquivalent(40),
    //width: getWidthEquivalent(SCREEN_WIDTH),
    //flexDirection: "row",
    alignItems: "center",
    //justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(15),
    marginTop: getHeightEquivalent(15),
    //borderWidth: 1,
  },
  tab: {
    flex: 1,
    paddingHorizontal: getWidthEquivalent(15),
    paddingVertical: getHeightEquivalent(8),
  },
  activeTab: {
    backgroundColor: colors.primary,
    borderRadius: 40,
  },
  tabText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
  },
  activeTabText: {
    color: colors.background,
  },
  listContainer: {
    flex: 1,
    paddingHorizontal: getWidthEquivalent(15),
    marginTop: getHeightEquivalent(20),
    paddingBottom: getHeightEquivalent(20),
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(60),
    paddingHorizontal: getWidthEquivalent(40),
  },
  emptyStateTitle: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: colors.text,
    textAlign: "center",
    marginTop: getHeightEquivalent(16),
    marginBottom: getHeightEquivalent(8),
  },
  emptyStateSubtitle: {
    fontSize: fontEq(16),
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: fontEq(22),
  },
  emptyTabStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(80),
    paddingHorizontal: getWidthEquivalent(40),
    minHeight: getHeightEquivalent(400),
  },
  emptyTabIconContainer: {
    marginBottom: getHeightEquivalent(24),
    opacity: 0.6,
  },
  emptyTabTitle: {
    fontSize: fontEq(22),
    fontWeight: "700",
    color: colors.text,
    textAlign: "center",
    marginBottom: getHeightEquivalent(12),
  },
  emptyTabSubtitle: {
    fontSize: fontEq(16),
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: fontEq(24),
    marginBottom: getHeightEquivalent(24),
  },
  comingSoonBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(8),
    borderRadius: 20,
  },
  comingSoonText: {
    color: colors.white,
    fontSize: fontEq(12),
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
});
