import { StyleSheet } from "react-native";
import { colors } from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
  SCREEN_WIDTH,
} from "../../../Utils/helpers";
const paint = colors;
export const CalanderScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: paint.white,
  },
  headerContainer: {
    height: getHeightEquivalent(60),
    width: "100%",
    borderColor: paint.border,
    backgroundColor: paint.white,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: getWidthEquivalent(5),
    paddingRight: getWidthEquivalent(15),
    marginBottom: getHeightEquivalent(10),
  },
  // New Header Styles
  newHeaderContainer: {
    height: getHeightEquivalent(60),
    width: "100%",
    backgroundColor: paint.white,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(16),
  },
  headerButton: {
    width: getWidthEquivalent(40),
    height: getWidthEquivalent(40),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: getWidthEquivalent(20),
  },
  dateContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: paint.background,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(8),
    borderRadius: getWidthEquivalent(20),
  },
  dateText: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: paint.text,
    marginRight: getWidthEquivalent(8),
  },
  rightHeaderContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(4),
  },
  notificationBadge: {
    position: "absolute",
    top: getHeightEquivalent(7),
    right: getWidthEquivalent(7),
    width: getWidthEquivalent(8),
    height: getWidthEquivalent(8),
    borderRadius: getWidthEquivalent(4),
    backgroundColor: "#FF4444",
  },
  profileButton: {
    width: getWidthEquivalent(36),
    height: getWidthEquivalent(36),
    borderRadius: getWidthEquivalent(18),
    backgroundColor: "#E8E4FF",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: getWidthEquivalent(4),
  },
  profileInitials: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: "#6B46C1",
  },
  headerText: {
    fontSize: fontEq(22),
    fontWeight: "600",
    color: paint.text,
    marginLeft: getWidthEquivalent(8),
    marginTop: getHeightEquivalent(15),
    alignSelf: "center",
    lineHeight: getHeightEquivalent(28),
    marginBottom: getHeightEquivalent(12),
  },
  addButton: {
    maxHeight: "95%",
    flexDirection: "row",
    minHeight: getHeightEquivalent(45),
    borderRadius: 12,
    width: getWidthEquivalent(80),
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: paint.primary,
    alignSelf: "center",
    paddingHorizontal: getWidthEquivalent(10),
  },
  addButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.white,
  },
  actionBar: {
    height: getHeightEquivalent(50),
    width: "100%",
    borderWidth: 1,
    borderColor: paint.border,
    backgroundColor: paint.background,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(15),
  },
  actionButton1: {
    //maxHeight: "95%",
    flexDirection: "row",
    //minHeight: getHeightEquivalent(45),
    paddingHorizontal: getWidthEquivalent(10),
    paddingVertical: getHeightEquivalent(10),
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: paint.white,
    borderColor: paint.border,
    // width: getWidthEquivalent(80),
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  actionButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.text,
  },
  bodyContainer: {
    flex: 1,
    backgroundColor: paint.white,
    flexDirection: "row",
  },
  calendarContainer: {
    //width: getWidthEquivalent(165),
    // paddingRight: getWidthEquivalent(20),
    //height: getHeightEquivalent(465),
    backgroundColor: paint.white,
    borderTopWidth: 1,
    borderTopColor: paint.border,
    overflow: "hidden",
    flexDirection: "row",
    flex: 1,
    position: "relative",
  },
  calendarHeader: {
    height: getHeightEquivalent(80),
    width: "100%",
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: paint.border,
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: getHeightEquivalent(8),
  },
  // Static header that doesn't scroll
  staticCalendarHeader: {
    height: getHeightEquivalent(80),
    width: "100%",
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: paint.border,
    alignItems: "center",
    justifyContent: "space-between",
    // paddingVertical: getHeightEquivalent(8),
    backgroundColor: paint.white,
    position: "relative",
    zIndex: 1,
  },
  headerLOGO: {
    width: getWidthEquivalent(51),
    height: "100%",
    resizeMode: "contain",
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderColor: paint.border,
  },
  staffImage: {
    height: getHeightEquivalent(36),
    width: getHeightEquivalent(36),
    borderRadius: 100,
    resizeMode: "cover",
    borderWidth: 1,
    borderColor: paint.border,
    marginRight: getWidthEquivalent(8),
  },
  staffName: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: paint.text,
    textAlign: "center",
  },
  // Staff info container styles
  staffInfoCenterContainer: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: getHeightEquivalent(4),
  },
  staffInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  // Page indicator styles for carousel
  pageIndicatorContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: getHeightEquivalent(16),
    backgroundColor: paint.white,
  },
  pageIndicator: {
    width: getWidthEquivalent(8),
    height: getWidthEquivalent(8),
    borderRadius: getWidthEquivalent(4),
    backgroundColor: paint.gray[300],
    marginHorizontal: getWidthEquivalent(4),
  },
  activePageIndicator: {
    backgroundColor: paint.primary,
    width: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(4),
  },
  // Staff navigation bar styles
  staffNavigationBar: {
    height: getHeightEquivalent(100),
    width: "100%",
    backgroundColor: paint.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 8,
    zIndex: 10,
  },
  staffNavButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: paint.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: paint.border,
  },
  disabledButton: {
    backgroundColor: paint.gray[100],
    borderColor: paint.gray[200],
  },
  staffInfoContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "red",
    height: "100%",
  },
  staffImageContainer: {
    height: getHeightEquivalent(36),
    width: getHeightEquivalent(36),
    borderRadius: getHeightEquivalent(18),
    backgroundColor: paint.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "lightgreen",
    marginBottom: getHeightEquivalent(8),
    shadowColor: "lightgreen",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.45,
    shadowRadius: 3,
    elevation: 5,
    zIndex: 10,
  },
  staffNavText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.text,
  },
  staffNavSubText: {
    fontSize: fontEq(12),
    fontWeight: "400",
    color: paint.textSecondary,
    marginTop: getHeightEquivalent(2),
  },
  // Header navigation button styles
  headerNavButton: {
    width: getWidthEquivalent(50),
    height: "100%",
    backgroundColor: paint.white,
    alignItems: "center",
    justifyContent: "center",
    borderColor: paint.border,
    marginHorizontal: getWidthEquivalent(6),
  },
  // Header pagination indicator styles
  headerPaginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: getHeightEquivalent(6),
    paddingVertical: getHeightEquivalent(4),
  },
  headerPageIndicator: {
    width: getWidthEquivalent(8),
    height: getWidthEquivalent(8),
    borderRadius: getWidthEquivalent(4),
    backgroundColor: paint.gray[400],
    marginHorizontal: getWidthEquivalent(4),
  },
  activeHeaderPageIndicator: {
    backgroundColor: paint.primary,
    width: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(4),
  },
  // Text pagination styles
  textPaginationContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: getWidthEquivalent(50),
    marginTop: getHeightEquivalent(6),
    paddingVertical: getHeightEquivalent(2),
  },
  paginationText: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: paint.textSecondary,
    backgroundColor: paint.gray[100],
    paddingHorizontal: getWidthEquivalent(4),
    paddingVertical: getHeightEquivalent(4),
    borderRadius: getWidthEquivalent(12),
    overflow: "hidden",
  },
  hourComponent: {
    width: getWidthEquivalent(65),
    height: getHeightEquivalent(80),
    backgroundColor: paint.white,
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderRightColor: paint.border,
    position: "relative",
    zIndex: 1,
  },
  hourText: {
    fontSize: fontEq(10),
    fontWeight: "700",
    color: paint.textSecondary,
    textAlign: "center",
    lineHeight: fontEq(12),
  },
  // Bottom Sheet Styles
  bottomSheetContent: {
    //flex: 1,
    //paddingHorizontal: getWidthEquivalent(20),
    paddingTop: getHeightEquivalent(10),
  },
  bottomSheetTitle: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: paint.text,
    textAlign: "center",
    marginBottom: getHeightEquivalent(20),
  },
  // Filter Panel Modal Styles
  filterPanelModal: {
    margin: 0,
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  filterPanel: {
    backgroundColor: paint.white,
    width: getWidthEquivalent(300),
    height: "100%",
    paddingTop: getHeightEquivalent(20),
  },
  filterPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(15),
    borderBottomWidth: 1,
    borderBottomColor: paint.border,
  },
  filterPanelTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: paint.text,
  },
  filterCloseButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: getWidthEquivalent(16),
    backgroundColor: paint.background,
  },
  filterPanelContent: {
    flex: 1,
    paddingVertical: getHeightEquivalent(20),
  },
  filterOption: {
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(15),
  },
  filterOptionText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.text,
    marginBottom: getHeightEquivalent(10),
  },
  filterPanelButtons: {
    flexDirection: "row",
    padding: getWidthEquivalent(20),
    borderTopWidth: 1,
    borderTopColor: paint.border,
    gap: getWidthEquivalent(12),
  },
  filterClearButton: {
    flex: 1,
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: paint.border,
    alignItems: "center",
    justifyContent: "center",
  },
  filterClearButtonText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: paint.textSecondary,
  },
  filterApplyButton: {
    flex: 1,
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    backgroundColor: paint.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  filterApplyButtonText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: paint.white,
  },

  // Menu Modal Styles
  modalContainer: {
    margin: 0,
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  panel: {
    backgroundColor: paint.white,
    width: getWidthEquivalent(280),
    height: "100%",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(15),
    borderBottomWidth: 1,
    borderBottomColor: paint.border,
  },
  title: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: paint.text,
  },
  closeButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: getWidthEquivalent(16),
    backgroundColor: paint.background,
  },
  content: {
    flex: 1,
    paddingVertical: getHeightEquivalent(10),
  },
  menuItem: {
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(15),
    borderBottomWidth: 1,
    borderBottomColor: paint.border,
  },
  menuItemText: {
    fontSize: fontEq(16),
    fontWeight: "500",
    color: paint.text,
  },

  // Empty State Styles
  emptyStateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: getWidthEquivalent(40),
    paddingVertical: getHeightEquivalent(60),
    backgroundColor: paint.white,
  },
  emptyStateTitle: {
    fontSize: fontEq(24),
    fontWeight: "700",
    color: paint.text,
    marginTop: getHeightEquivalent(24),
    textAlign: "center",
  },
  emptyStateSubtitle: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.primary,
    marginTop: getHeightEquivalent(8),
    textAlign: "center",
  },
  emptyStateDescription: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: paint.textSecondary,
    marginTop: getHeightEquivalent(12),
    textAlign: "center",
    lineHeight: fontEq(20),
  },
  emptyStateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: paint.primary,
    paddingHorizontal: getWidthEquivalent(24),
    paddingVertical: getHeightEquivalent(14),
    borderRadius: getWidthEquivalent(12),
    marginTop: getHeightEquivalent(32),
    gap: getWidthEquivalent(8),
    shadowColor: paint.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  emptyStateButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: paint.white,
  },
});
