import { StyleSheet } from "react-native";
import { colors } from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../../Utils/helpers";

export const CreateAppointmentStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  content: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.white,
  },
  backButton: {
    width: getWidthEquivalent(40),
    height: getWidthEquivalent(40),
    borderRadius: getWidthEquivalent(20),
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.text,
    flex: 1,
    textAlign: "left",
  },
  headerSpacer: {
    width: getWidthEquivalent(40),
  },
  headerDateTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    paddingHorizontal: getWidthEquivalent(12),
    paddingVertical: getHeightEquivalent(6),
    borderRadius: getWidthEquivalent(20),
    gap: getWidthEquivalent(6),
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerDateTimeContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(4),
  },
  headerDateText: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: colors.text,
  },
  headerTimeText: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: colors.primary,
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: getWidthEquivalent(16),
  },
  section: {
    marginTop: getHeightEquivalent(12),
  },
  sectionCard: {
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(16),
    padding: getWidthEquivalent(16),
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.black,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    gap: getHeightEquivalent(12),
  },
  sectionTitle: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(12),
    marginTop: getHeightEquivalent(12),
  },
  dateTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
  },
  dateTimeInfo: {
    flex: 1,
  },
  dateTimeLabel: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: colors.textSecondary,
    marginBottom: getHeightEquivalent(4),
  },
  dateTimeValue: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(2),
  },
  timeValue: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: colors.primary,
  },
  editButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(16),
  },
  searchIcon: {
    marginRight: getWidthEquivalent(12),
  },
  searchInput: {
    flex: 1,
    paddingVertical: getHeightEquivalent(12),
    fontSize: fontEq(16),
    color: colors.text,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(12),
    marginBottom: getHeightEquivalent(16),
    gap: getWidthEquivalent(8),
  },
  addButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  clientList: {
    maxHeight: getHeightEquivalent(200),
  },
  clientItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.white,
  },
  selectedClientItem: {
    borderColor: colors.primary,
    backgroundColor: colors.primary + "10",
  },
  clientInfo: {
    flex: 1,
  },
  clientName: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
  },
  clientEmail: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.textSecondary,
    marginTop: getHeightEquivalent(2),
  },
  selectedIndicator: {
    width: getWidthEquivalent(24),
    height: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(12),
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedIndicatorText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: colors.white,
  },
  addServiceButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primary,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(12),
    marginBottom: getHeightEquivalent(16),
    gap: getWidthEquivalent(8),
  },
  addServiceButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.primary,
  },
  selectedServicesContainer: {
    marginTop: getHeightEquivalent(8),
  },
  selectedServiceItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    marginBottom: getHeightEquivalent(8),
  },
  serviceInfo: {
    flex: 1,
  },
  serviceName: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
  },
  servicePrice: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: colors.primary,
    marginTop: getHeightEquivalent(2),
  },
  removeButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.danger,
  },
  noServicesText: {
    fontSize: fontEq(16),
    fontWeight: "400",
    color: colors.textSecondary,
    textAlign: "center",
    marginTop: getHeightEquivalent(8),
  },
  noServicesContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: getHeightEquivalent(24),
    gap: getHeightEquivalent(8),
  },
  bottomSection: {
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
  },
  totalContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: getHeightEquivalent(16),
  },
  totalLabel: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.text,
  },
  totalAmount: {
    fontSize: fontEq(18),
    fontWeight: "700",
    color: colors.primary,
  },
  saveButton: {
    backgroundColor: colors.primary,
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  disabledSaveButton: {
    backgroundColor: colors.gray[300],
  },
  saveButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  serviceModal: {
    margin: 0,
    justifyContent: "flex-end",
  },
  serviceModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: getWidthEquivalent(20),
    borderTopRightRadius: getWidthEquivalent(20),
    height: "90%",
    paddingHorizontal: getWidthEquivalent(16),
    paddingBottom: getHeightEquivalent(20),
  },
  serviceSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(16),
    marginHorizontal: getWidthEquivalent(16),
  },
  serviceSearchInput: {
    flex: 1,
    paddingVertical: getHeightEquivalent(12),
    fontSize: fontEq(16),
    color: colors.text,
  },
  serviceList: {
    maxHeight: getHeightEquivalent(500),
    marginHorizontal: getWidthEquivalent(16),
  },
  serviceItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.white,
  },
  serviceDuration: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.textSecondary,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: getWidthEquivalent(16),
  },
  emptyStateTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(8),
  },
  emptyStateSubtitle: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.textSecondary,
    marginBottom: getHeightEquivalent(16),
  },
  addFirstClientButton: {
    backgroundColor: colors.primary,
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  addFirstClientText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  clientCardContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.white,
  },
  clientImageContainer: {
    width: getWidthEquivalent(48),
    height: getWidthEquivalent(48),
    borderRadius: getWidthEquivalent(24),
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  clientInitials: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  clientDetailsContainer: {
    flex: 1,
    marginLeft: getWidthEquivalent(16),
  },
  clientPhone: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.textSecondary,
    marginTop: getHeightEquivalent(2),
  },
  loadMoreButton: {
    backgroundColor: colors.primary,
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  clearButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  loadMoreText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  checkboxContainer: {
    width: getWidthEquivalent(40),
    alignItems: "center",
    justifyContent: "center",
  },
  checkbox: {
    width: getWidthEquivalent(24),
    height: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(6),
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    height: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(6),
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxCheckedIcon: {
    width: getWidthEquivalent(16),
    height: getWidthEquivalent(16),
    borderRadius: getWidthEquivalent(4),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: getWidthEquivalent(16),
  },
  loadingText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginTop: getHeightEquivalent(8),
  },
  selectedClientContainer: {
    marginBottom: getHeightEquivalent(16),
  },
  selectedClientCard: {
    backgroundColor: colors.primary + "10",
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.primary,
    padding: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(12),
  },
  selectedClientContent: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: getHeightEquivalent(12),
  },
  selectedClientAvatar: {
    width: getWidthEquivalent(56),
    height: getWidthEquivalent(56),
    borderRadius: getWidthEquivalent(28),
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: getWidthEquivalent(12),
  },
  selectedClientInitials: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: colors.white,
    textTransform: "uppercase",
  },
  selectedClientInfo: {
    flex: 1,
  },
  selectedClientPhone: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: colors.text,
    marginTop: getHeightEquivalent(2),
  },
  selectedClientName: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(4),
  },
  selectedClientEmail: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.textSecondary,
  },
  viewProfileButton: {
    marginTop: getHeightEquivalent(12),
    paddingVertical: getHeightEquivalent(8),
    paddingHorizontal: getWidthEquivalent(16),
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: colors.primary,
    alignSelf: "flex-start",
    width: "100%",
    alignItems: "center",
  },
  viewProfileText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: colors.primary,
  },
  changeClientButton: {
    backgroundColor: colors.gray[200],
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(16),
    borderRadius: getWidthEquivalent(8),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  changeClientText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: colors.text,
  },
  servicesLoadMoreButton: {
    marginTop: getHeightEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  servicesLoadMoreText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: colors.primary,
  },
  modalDragIndicator: {
    width: getWidthEquivalent(40),
    height: getHeightEquivalent(5),
    borderRadius: getWidthEquivalent(3),
    backgroundColor: colors.gray[300],
    alignSelf: "center",
    marginTop: getHeightEquivalent(10),
    marginBottom: getHeightEquivalent(15),
  },
  modalDoneButton: {
    backgroundColor: colors.primary,
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    marginHorizontal: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(20),
    marginTop: getHeightEquivalent(10),
    alignItems: "center",
    justifyContent: "center",
  },
  modalDoneButtonDisabled: {
    opacity: 0.5,
  },
  modalDoneButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  serviceModalTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.text,
    textAlign: "left",
    marginBottom: getHeightEquivalent(20),
  },
  pickerContainer: {
    backgroundColor: colors.background,
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  picker: {
    height: getHeightEquivalent(50),
    width: "100%",
  },
  durationInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    marginBottom: getHeightEquivalent(12),
    borderWidth: 1,
    borderColor: colors.primary + "20",
  },
  durationLabel: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: colors.text,
  },
  durationValue: {
    fontSize: fontEq(16),
    fontWeight: "700",
    color: colors.primary,
  },
  selectionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: getHeightEquivalent(12)
  },
  selectionButtonDisabled: {
    opacity: 0.5,
    backgroundColor: colors.gray[100],
  },
  selectionButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: getWidthEquivalent(12),
  },
  selectionButtonText: {
    fontSize: fontEq(16),
    fontWeight: "500",
    color: colors.text,
    flex: 1,
  },
  selectionButtonPlaceholder: {
    color: colors.textSecondary,
  },
  selectionButtonDisabledText: {
    color: colors.textSecondary,
  },
  modalList: {
    maxHeight: getHeightEquivalent(400),
  },
  modalListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.background,
    gap: getWidthEquivalent(12),
  },
  modalListItemSelected: {
    backgroundColor: colors.primary + "15",
    borderWidth: 1,
    borderColor: colors.primary,
  },
  modalListItemText: {
    fontSize: fontEq(16),
    fontWeight: "500",
    color: colors.text,
    flex: 1,
  },
  modalListItemTextSelected: {
    color: colors.primary,
    fontWeight: "600",
  },
  // Client Selection Card Styles
  clientSelectionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
    gap: getWidthEquivalent(12),
  },
  clientCardAvatar: {
    width: getWidthEquivalent(50),
    height: getWidthEquivalent(50),
    borderRadius: getWidthEquivalent(25),
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  clientCardInitials: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.white,
  },
  clientPlaceholderAvatar: {
    width: getWidthEquivalent(50),
    height: getWidthEquivalent(50),
    borderRadius: getWidthEquivalent(25),
    backgroundColor: colors.gray[200],
    alignItems: "center",
    justifyContent: "center",
  },
  clientCardInfo: {
    flex: 1,
  },
  clientCardName: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(4),
  },
  clientCardPhone: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.textSecondary,
  },
  clientCardPlaceholder: {
    fontSize: fontEq(16),
    fontWeight: "500",
    color: colors.textSecondary,
    marginBottom: getHeightEquivalent(4),
  },
  clientCardSubtext: {
    fontSize: fontEq(13),
    fontWeight: "400",
    color: colors.textSecondary,
  },
  // Client Modal Styles
  clientModal: {
    justifyContent: "flex-end",
    margin: 0,
  },
  clientModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: getWidthEquivalent(24),
    borderTopRightRadius: getWidthEquivalent(24),
    paddingHorizontal: getWidthEquivalent(20),
    paddingBottom: getHeightEquivalent(20),
    paddingTop: getHeightEquivalent(12),
    height: "90%",
  },
  clientModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: getHeightEquivalent(16),
  },
  clientModalTitle: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: colors.text,
  },
  clientModalCloseButton: {
    padding: getWidthEquivalent(8),
  },
  clientModalList: {
    flex: 1,
    marginTop: getHeightEquivalent(12),
  },
});
