import { Platform, StyleSheet } from "react-native";
import { colors } from "../../../Constants/colors";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../../Utils/helpers";

export const CreateAppointmentStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  content: {
    flex: 1,
  },
  add: {
    width: getWidthEquivalent(60),
    height: getWidthEquivalent(60),
    borderRadius: getWidthEquivalent(50),
    backgroundColor: "#f5e7fd",
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.white,
  },
  backButton: {
    width: getWidthEquivalent(40),
    height: getWidthEquivalent(40),
    //borderRadius: getWidthEquivalent(20),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(18),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
    flex: 1,
    textAlign: "left",
  },
  headerSpacer: {
    width: getWidthEquivalent(40),
  },
  headerDateTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    paddingHorizontal: getWidthEquivalent(12),
    paddingVertical: getHeightEquivalent(4),
    borderRadius: getWidthEquivalent(20),
    gap: getWidthEquivalent(6),
    borderWidth: 1,
    borderColor: colors.gray[300],
  },
  headerDateTimeContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(4),
  },
  headerDateText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
  },
  headerTimeText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.black,
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: getWidthEquivalent(16),
  },
  section: {
    marginTop: getHeightEquivalent(12),
  },
  sectionCard: {
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(16),
    padding: getWidthEquivalent(16),
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.black,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    gap: getHeightEquivalent(12),
  },
  sectionTitle: {
     fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.black,
    marginBottom: getHeightEquivalent(12),
    marginTop: getHeightEquivalent(12),
  },
  dateTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
  },
  dateTimeInfo: {
    flex: 1,
  },
  dateTimeLabel: {
    fontSize: fontEq(12),
    fontWeight: "500",
    color: colors.textSecondary,
    marginBottom: getHeightEquivalent(4),
  },
  dateTimeValue: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(2),
  },
  timeValue: {
    fontSize: fontEq(14),
    fontWeight: "500",
    color: colors.primary,
  },
  editButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(10),
    borderWidth: 1,
    borderColor: colors.gray[300],
    paddingHorizontal: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(16),
  },
  searchIcon: {
    marginRight: getWidthEquivalent(12),
  },
  searchInput: {
    flex: 1,
    paddingVertical: getHeightEquivalent(12),
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: colors.white,
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(50),
    marginBottom: getHeightEquivalent(16),
    gap: getWidthEquivalent(8),
    // borderWidth: 1,
    // borderColor: colors.gray[300],
  },
  addButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(18),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.black,
  },
  clientList: {
    maxHeight: getHeightEquivalent(200),
  },
  clientItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.white,
  },
  selectedClientItem: {
    borderColor: colors.primary,
    backgroundColor: colors.primary + "10",
  },
  clientInfo: {
    flex: 1,
  },
  clientName: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.text,
  },
  clientEmail: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.textSecondary,
    marginTop: getHeightEquivalent(2),
  },
  selectedIndicator: {
    width: getWidthEquivalent(24),
    height: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(12),
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedIndicatorText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: colors.white,
  },
  addServiceButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray[300],
    paddingHorizontal: getWidthEquivalent(14),
    paddingVertical: getHeightEquivalent(8),
    borderRadius: getWidthEquivalent(50),
    marginBottom: getHeightEquivalent(16),
    gap: getWidthEquivalent(8),
    width: "45%",
  },
  centerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  addServiceButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "500",
    color: colors.black,
  },
  selectedServicesContainer: {
    marginTop: getHeightEquivalent(8),
  },
  selectedServiceItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.white,
    borderLeftWidth: 4,
    borderColor: "#3C096C",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(4),
    marginBottom: getHeightEquivalent(8),
  },
  serviceInfo: {
    flex: 1,
  },
  serviceName: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "500",
    color: colors.black,
  },
  servicePrice: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "600",
    color: colors.black,
    marginTop: getHeightEquivalent(2),
    // marginLeft: getWidthEquivalent(6),
  },
  removeButton: {
    width: getWidthEquivalent(22),
    height: getWidthEquivalent(22),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 5,
    //   borderWidth: 1,
    borderColor: colors.danger,
  },
  noServicesText: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.textSecondary,
    textAlign: "center",
    marginTop: getHeightEquivalent(8),
  },
  noServicesContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: getHeightEquivalent(44),
    gap: getHeightEquivalent(8),
  },
  AddIcon: {
    borderWidth: 1,
    borderRadius: 50,
  },
  bottomSection: {
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
  },
  totalContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: getHeightEquivalent(16),
  },
  totalLabel: {
  fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.black,
  },
  totalAmount: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.black,
  },
  saveButton: {
    backgroundColor: colors.black,
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(50),
    borderWidth: 1,
    borderColor: colors.gray[300],
    alignItems: "center",
    justifyContent: "center",
  },
  Label: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.gray[600],
  },
  disabledSaveButton: {
    backgroundColor: colors.gray[300],
  },
  saveButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "700",
    color: colors.white,
  },
  serviceModal: {
    margin: 0,
    justifyContent: "flex-end",
  },
  serviceModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: getWidthEquivalent(20),
    borderTopRightRadius: getWidthEquivalent(20),
    height: "90%",
    paddingHorizontal: getWidthEquivalent(16),
    paddingBottom: getHeightEquivalent(20),
  },
  serviceSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: getWidthEquivalent(10),
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(16),
    marginHorizontal: getWidthEquivalent(16),
  },
  serviceSearchInput: {
    flex: 1,
    paddingVertical: getHeightEquivalent(12),
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    color: colors.text,
  },
  serviceList: {
    maxHeight: getHeightEquivalent(500),
    marginHorizontal: getWidthEquivalent(16),
  },
  serviceItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(4),
    borderLeftWidth: 4,
    borderColor: "#3C096C",
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.white,
  },
  serviceDuration: {
  fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(12),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.textSecondary,
    marginLeft: getWidthEquivalent(5),
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: getWidthEquivalent(16),
  },
  emptyStateTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(18),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(8),
  },
  emptyStateSubtitle: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.textSecondary,
    marginBottom: getHeightEquivalent(16),
  },
  addFirstClientButton: {
    backgroundColor: colors.primary,
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  addFirstClientText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  clientCardContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(8),
    borderRadius: getWidthEquivalent(8),
    //  borderWidth: 1,
    //  borderColor: colors.border,
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.white,
  },
  clientImageContainer: {
    width: getWidthEquivalent(60),
    height: getWidthEquivalent(60),
    borderRadius: getWidthEquivalent(50),
    backgroundColor: "#f5e7fd",
    alignItems: "center",
    justifyContent: "center",
  },
  clientInitials: {
     fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: "#3C096C",
  },
  clientDetailsContainer: {
    flex: 1,
    marginLeft: getWidthEquivalent(16),
  },
  clientPhone: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.textSecondary,
    marginTop: getHeightEquivalent(2),
  },
  loadMoreButton: {
    backgroundColor: colors.white,
    paddingVertical: getHeightEquivalent(12),
    paddingHorizontal: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.gray[300],
    alignItems: "center",
    justifyContent: "center",
  },
  clearButton: {
    width: getWidthEquivalent(32),
    height: getWidthEquivalent(32),
    borderRadius: getWidthEquivalent(16),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  loadMoreText: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.black,
  },
  checkboxContainer: {
    width: getWidthEquivalent(40),
    alignItems: "center",
    justifyContent: "center",
  },
  checkbox: {
    width: getWidthEquivalent(24),
    height: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(6),
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    height: getWidthEquivalent(24),
    borderRadius: getWidthEquivalent(6),
    backgroundColor: "#3C096C",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxCheckedIcon: {
    width: getWidthEquivalent(16),
    height: getWidthEquivalent(16),
    borderRadius: getWidthEquivalent(4),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: getWidthEquivalent(16),
  },
  loadingText: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
    marginTop: getHeightEquivalent(8),
  },
  selectedClientContainer: {
    marginBottom: getHeightEquivalent(16),
  },
  selectedClientCard: {
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.gray[300],
    padding: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(12),
    marginTop: getHeightEquivalent(12),
  },
  selectedClientContent: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: getHeightEquivalent(12),
  },
  selectedClientAvatar: {
    width: getWidthEquivalent(60),
    height: getWidthEquivalent(60),
    borderRadius: getWidthEquivalent(50),
    backgroundColor: "#f5e7fd",
    alignItems: "center",
    justifyContent: "center",
    marginRight: getWidthEquivalent(12),
  },
  selectedClientInitials: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: "#3C096C",
    textTransform: "uppercase",
  },
  selectedClientInfo: {
    flex: 1,
  },
  selectedClientPhone: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "500",
    color: colors.text,
    marginTop: getHeightEquivalent(2),
  },
  selectedClientName: {
    fontSize:Platform.OS === 'android' ?fontEq(14): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(4),
  },
  selectedClientEmail: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "400",
    color: colors.textSecondary,
  },
  viewProfileButton: {
    marginTop: getHeightEquivalent(12),
    paddingVertical: getHeightEquivalent(8),
    paddingHorizontal: getWidthEquivalent(16),
    //backgroundColor: colors.gray[100],
    borderRadius: getWidthEquivalent(8),
    borderWidth: 1,
    borderColor: colors.gray[300],
    alignSelf: "flex-start",
    width: "100%",
    alignItems: "center",
  },
  viewProfileText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.black,
  },
  changeClientButton: {
    // backgroundColor: colors.gray[100],
    paddingVertical: getHeightEquivalent(10),
    paddingHorizontal: getWidthEquivalent(16),
    borderRadius: getWidthEquivalent(10),
    borderColor: colors.gray[300],
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  changeClientText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
  },
  servicesLoadMoreButton: {
    marginTop: getHeightEquivalent(16),
    paddingVertical: getHeightEquivalent(12),
    alignItems: "center",
    justifyContent: "center",
  },
  servicesLoadMoreText: {
    fontSize: fontEq(14),
    fontWeight: "600",
    color: colors.primary,
  },
  modalDragIndicator: {
    width: getWidthEquivalent(40),
    height: getHeightEquivalent(5),
    borderRadius: getWidthEquivalent(3),
    backgroundColor: colors.gray[300],
    alignSelf: "center",
    marginTop: getHeightEquivalent(10),
    marginBottom: getHeightEquivalent(15),
  },
  modalDoneButton: {
    backgroundColor: colors.black,
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(50),
    borderWidth: 1,
    borderColor: colors.gray[300],
    marginHorizontal: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(20),
    marginTop: getHeightEquivalent(10),
    alignItems: "center",
    justifyContent: "center",
  },
  modalDoneButtonDisabled: {
    opacity: 0.5,
  },
  modalDoneButtonText: {
  fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.white,
  },
  serviceModalTitle: {
    fontSize:Platform.OS === 'android' ?fontEq(16): fontEq(18),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.text,
    textAlign: "left",
    marginBottom: getHeightEquivalent(20),
  },
  pickerContainer: {
    backgroundColor: colors.background,
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  picker: {
    height: getHeightEquivalent(50),
    width: "100%",
  },
  durationInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.white,
    // paddingHorizontal: getWidthEquivalent(16),
    // paddingVertical: getHeightEquivalent(12),
    borderRadius: getWidthEquivalent(8),
    marginBottom: getHeightEquivalent(12),
    // borderWidth: 1,
    borderColor: colors.border,
  },
  durationLabel: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "500",
    color: colors.black,
  },
  durationValue: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(12),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "500",
    color: colors.black,
  },
  selectionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.gray[50],
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(5),
    borderLeftWidth: 4,
    borderColor: "#3C096C",
    marginBottom: getHeightEquivalent(12),
  },
  selectionButtonDisabled: {
    opacity: 0.5,
    backgroundColor: colors.gray[100],
  },
  selectionButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: getWidthEquivalent(12),
  },
  selectionButtonText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "500",
    color: colors.text,
    flex: 1,
  },
  selectionButtonPlaceholder: {
    color: colors.textSecondary,
  },
  selectionButtonDisabledText: {
    color: colors.textSecondary,
  },
  modalList: {
    maxHeight: "100%",
  },
  fullHeightModalList: {
    flexGrow: 1,
    marginHorizontal: getWidthEquivalent(16),
  },
  modalListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: getWidthEquivalent(16),
    paddingVertical: getHeightEquivalent(16),
    borderRadius: getWidthEquivalent(12),
    marginBottom: getHeightEquivalent(8),
    backgroundColor: colors.background,
    gap: getWidthEquivalent(12),
  },
  modalListItemSelected: {
    backgroundColor: colors.primary + "15",
    borderWidth: 1,
    borderColor: colors.primary,
  },
  modalListItemText: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(14),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "500",
    color: colors.text,
    flex: 1,
  },
  modalListItemTextSelected: {
    color: colors.primary,
    fontWeight: "600",
  },
  // Client Selection Card Styles
  clientSelectionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    paddingHorizontal: getWidthEquivalent(22),
    paddingVertical: getHeightEquivalent(22),
    borderRadius: getWidthEquivalent(12),
    borderWidth: 1,
    borderColor: colors.gray[300],
    gap: getWidthEquivalent(12),
  },
  clientCardAvatar: {
    width: getWidthEquivalent(50),
    height: getWidthEquivalent(50),
    borderRadius: getWidthEquivalent(25),
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  clientCardInitials: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.white,
  },
  clientPlaceholderAvatar: {
    width: getWidthEquivalent(60),
    height: getWidthEquivalent(60),
    borderRadius: getWidthEquivalent(50),
    backgroundColor: "#f5e7fd",
    alignItems: "center",
    justifyContent: "center",
  },
  clientCardInfo: {
    flex: 1,
  },
  clientCardName: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(4),
  },
  clientCardPhone: {
    fontSize: fontEq(14),
    fontWeight: "400",
    color: colors.textSecondary,
  },
  clientCardPlaceholder: {
    fontSize:Platform.OS === 'android' ?fontEq(12): fontEq(16),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "500",
    color: colors.black,
    marginBottom: getHeightEquivalent(4),
  },
  clientCardSubtext: {
    fontSize:Platform.OS === 'android' ?fontEq(10): fontEq(13),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : undefined,
    fontWeight: "400",
    color: colors.textSecondary,
  },
  // Client Modal Styles
  clientModal: {
    justifyContent: "flex-end",
    margin: 0,
  },
  clientModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: getWidthEquivalent(24),
    borderTopRightRadius: getWidthEquivalent(24),
    paddingHorizontal: getWidthEquivalent(20),
    paddingBottom: getHeightEquivalent(20),
    paddingTop: getHeightEquivalent(12),
    height: "90%",
  },
  clientModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: getHeightEquivalent(16),
  },
  clientModalTitle: {
     fontSize:Platform.OS === 'android' ?fontEq(18): fontEq(24),
    fontFamily: Platform.OS === 'android' ? 'sans-serif-condensed' : 'Helvetica',
    fontWeight: "600",
    color: colors.black,
  },
  clientModalCloseButton: {
    padding: getWidthEquivalent(8),
  },
  clientModalList: {
    flex: 1,
    marginTop: getHeightEquivalent(12),
  },
  // Saving Overlay Styles
  savingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  savingOverlayContent: {
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(20),
    padding: getWidthEquivalent(32),
    alignItems: "center",
    justifyContent: "center",
    minWidth: getWidthEquivalent(200),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  savingOverlayText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginTop: getHeightEquivalent(16),
    textAlign: "center",
  },
});
