import { StyleSheet } from "react-native";
import { getHeightEquivalent, getWidthEquivalent, fontEq } from "../../../Utils/helpers";
import { colors } from "../../../Constants/colors";

export const PaymentMethodsScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(16),
    backgroundColor: colors.primary,
  },
  backButton: {
    width: getWidthEquivalent(40),
    height: getHeightEquivalent(40),
    borderRadius: getWidthEquivalent(20),
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  headerTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.white,
  },
  headerSpacer: {
    width: getWidthEquivalent(40),
  },
  content: {
    flex: 1,
    backgroundColor: colors.white,
    borderTopLeftRadius: getWidthEquivalent(24),
    borderTopRightRadius: getWidthEquivalent(24),
    paddingTop: getHeightEquivalent(24),
    paddingHorizontal: getWidthEquivalent(20),
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: getWidthEquivalent(12),
    paddingVertical: getHeightEquivalent(16),
    paddingHorizontal: getWidthEquivalent(20),
    marginBottom: getHeightEquivalent(24),
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  addButtonIcon: {
    width: getWidthEquivalent(40),
    height: getHeightEquivalent(40),
    borderRadius: getWidthEquivalent(20),
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: getWidthEquivalent(12),
  },
  addButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  paymentMethodsList: {
    marginBottom: getHeightEquivalent(24),
  },
  paymentMethodCard: {
    backgroundColor: colors.white,
    borderRadius: getWidthEquivalent(12),
    padding: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(12),
    borderWidth: 1,
    borderColor: colors.gray[200],
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  paymentMethodHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  paymentMethodInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  paymentMethodIcon: {
    width: getWidthEquivalent(48),
    height: getHeightEquivalent(48),
    borderRadius: getWidthEquivalent(24),
    backgroundColor: colors.gray[50],
    alignItems: "center",
    justifyContent: "center",
    marginRight: getWidthEquivalent(12),
  },
  paymentMethodDetails: {
    flex: 1,
  },
  paymentMethodName: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.text,
    marginBottom: getHeightEquivalent(4),
  },
  paymentMethodDetails: {
    fontSize: fontEq(14),
    color: colors.textSecondary,
    marginBottom: getHeightEquivalent(2),
  },
  paymentMethodActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: getWidthEquivalent(8),
  },
  defaultBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: getWidthEquivalent(12),
    paddingHorizontal: getWidthEquivalent(8),
    paddingVertical: getHeightEquivalent(4),
    marginRight: getWidthEquivalent(8),
  },
  defaultBadgeText: {
    fontSize: fontEq(12),
    fontWeight: "600",
    color: colors.white,
    marginLeft: getWidthEquivalent(4),
  },
  actionButton: {
    width: getWidthEquivalent(36),
    height: getHeightEquivalent(36),
    borderRadius: getWidthEquivalent(18),
    backgroundColor: colors.gray[100],
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: getHeightEquivalent(60),
  },
  emptyStateTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.text,
    marginTop: getHeightEquivalent(16),
    marginBottom: getHeightEquivalent(8),
  },
  emptyStateDescription: {
    fontSize: fontEq(14),
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: getHeightEquivalent(20),
  },
  securityNotice: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray[50],
    borderRadius: getWidthEquivalent(12),
    padding: getWidthEquivalent(16),
    marginBottom: getHeightEquivalent(24),
  },
  securityNoticeText: {
    fontSize: fontEq(14),
    color: colors.textSecondary,
    marginLeft: getWidthEquivalent(8),
    flex: 1,
  },
});
