import { StyleSheet } from "react-native";
import { getHeightEquivalent, getWidthEquivalent, fontEq } from "../../../Utils/helpers";
import { colors } from "../../../Constants/colors";

export const PaymentProcessingScreenStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: getWidthEquivalent(20),
    paddingVertical: getHeightEquivalent(16),
    backgroundColor: colors.primary,
  },
  backButton: {
    width: getWidthEquivalent(40),
    height: getHeightEquivalent(40),
    borderRadius: getWidthEquivalent(20),
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  headerTitle: {
    fontSize: fontEq(18),
    fontWeight: "600",
    color: colors.white,
  },
  headerSpacer: {
    width: getWidthEquivalent(40),
  },
  content: {
    flex: 1,
    backgroundColor: colors.white,
  },
  processingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: getWidthEquivalent(40),
  },
  processingTitle: {
    fontSize: fontEq(20),
    fontWeight: "600",
    color: colors.text,
    marginTop: getHeightEquivalent(24),
    marginBottom: getHeightEquivalent(8),
  },
  processingDescription: {
    fontSize: fontEq(16),
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: getHeightEquivalent(24),
  },
  statusContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: getWidthEquivalent(40),
  },
  statusTitle: {
    fontSize: fontEq(24),
    fontWeight: "700",
    color: colors.text,
    marginTop: getHeightEquivalent(24),
    marginBottom: getHeightEquivalent(12),
    textAlign: "center",
  },
  statusDescription: {
    fontSize: fontEq(16),
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: getHeightEquivalent(24),
    marginBottom: getHeightEquivalent(32),
  },
  continueButton: {
    backgroundColor: colors.primary,
    borderRadius: getWidthEquivalent(12),
    paddingVertical: getHeightEquivalent(16),
    paddingHorizontal: getWidthEquivalent(32),
    alignItems: "center",
    justifyContent: "center",
    minWidth: getWidthEquivalent(200),
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  continueButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  retryButton: {
    backgroundColor: colors.primary,
    borderRadius: getWidthEquivalent(12),
    paddingVertical: getHeightEquivalent(16),
    paddingHorizontal: getWidthEquivalent(32),
    alignItems: "center",
    justifyContent: "center",
    minWidth: getWidthEquivalent(200),
    marginBottom: getHeightEquivalent(16),
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  retryButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.white,
  },
  cancelButton: {
    backgroundColor: "transparent",
    borderRadius: getWidthEquivalent(12),
    paddingVertical: getHeightEquivalent(16),
    paddingHorizontal: getWidthEquivalent(32),
    alignItems: "center",
    justifyContent: "center",
    minWidth: getWidthEquivalent(200),
    borderWidth: 1,
    borderColor: colors.gray[300],
  },
  cancelButtonText: {
    fontSize: fontEq(16),
    fontWeight: "600",
    color: colors.textSecondary,
  },
  webView: {
    flex: 1,
  },
  webViewLoading: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  webViewLoadingText: {
    fontSize: fontEq(16),
    color: colors.textSecondary,
    marginTop: getHeightEquivalent(16),
  },
});
